name: EternalSkills
version: 1.0.0
description: A plugin to trigger various skills on player actions.
author: Elias
main: com.afelia.eskills.Eskills
api-version: '1.20'
depend: [MythicMobs]
commands:
  eskills:
    description: Manage player skills and tags
    usage: /eskills tag add <tag> <player> | /eskills tag remove <tag> <player> | /eskills tag clear <player>
    permission: mythicskill.tag
permissions:
  mythicskill.trigger:
    description: Allows players to trigger skills.
    default: true
