name: EternalSkills
version: 1.0.0
description: A plugin to trigger various skills on player actions.
author: Elias
main: com.afelia.eternalskills.EternalSkills
api-version: '1.20'
depend: [MythicMobs, PlaceholderAPI]
commands:
  eskills:
    description: ESkills

permissions:
  mythicskill.trigger:
    description: Allows players to trigger skills.
    default: true
